version: '3.4'

services:
  grasindo.api.products:
    image: grasindo.api.products
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:1337"
    networks:
      - grasindo.api
    environment:
      DB_NAME: grasindo_products
      DB_USER: mypgadmin
      DB_PASS: password


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: grasindo_products
      POSTGRES_USER: mypgadmin
      POSTGRES_PASSWORD: password
    networks:
      - grasindo.api

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
    networks:
      - grasindo.api



networks: 
  grasindo.api: