version: '3.4'

services:
  grasindo.api.products:
    image: grasindo.api.products
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    networks:
      - grasindo.api
    environment:
      DB_NAME: grasindo_products
      DB_USER: mypgadmin
      DB_PASS: password
    volumes:
      - go-modules:/go/pkg/mod 
    depends_on:
      - db


  db:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_DB: grasindo_products
      POSTGRES_USER: mypgadmin
      POSTGRES_PASSWORD: password
    networks:
      - grasindo.api

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - grasindo.api


volumes:
  go-modules: # Define the volume
  
networks: 
  grasindo.api: