version: '3.4'

services:
  grasindo.api.products:
    image: grasindo.api.products
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "55551:55551"
    networks: 
      - grasindo.api


networks: 
  grasindo.api: