version: '3.4'

services:
  grasindo.api.products:
    image: grasindo.api.products
    build:
      context: .
      dockerfile: Dockerfile
    expose: 
      - "8080"
    ports:
      - "1337:8080"



networks: 
  grasindo.api: